---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/pythonapp/
    - /bin/mkdir $DEPLOYPATH
    - /bin/cp app.py $DEPLOYPATH
    - /bin/cp passenger_wsgi.py $DEPLOYPATH
    - /bin/cp requirements.txt $DEPLOYPATH
    - /bin/mkdir $DEPLOYPATH/tmp
    - /bin/touch $DEPLOYPATH/tmp/restart.txt
